project_name: graken
env:
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  -
    binary: graken
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386

release:
  draft: true

archives:
  -
    id: "graken"
    builds: ['graken']
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
